name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 1.1.0
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  uuid:  "^3.0.0"
  http: ^0.13.1
  path: "^1.6.2"
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.3.0"
