name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 1.1.0
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  uuid:  "^2.0.0"
  http: ^0.13.1
  path: "^1.6.2"
  sqflite: "^1.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.3.0"
